//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Tra.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDR_TRATYPE                     129
#define IDD_OPT_SETTING                 130
#define IDD_OPT_MOCA                    130
#define IDD_DLG_FIND                    131
#define IDR_TOOLBAR                     137
#define IDD_FIND_LIST                   139
#define IDR_MENU_PERFORMANCE            140
#define IDD_IN_PROGRESS                 141
#define IDI_ICON1                       142
#define IDI_ICON2                       143
#define IDD_DLG_GRAPH                   144
#define IDD_OPT_MTF                     145
#define IDD_OPT_COLOR                   146
#define IDB_BMP_CLOSE                   146
#define IDB_BMP_OPEN                    147
#define IDI_ICN_OPEN                    151
#define IDI_ICN_CLOSE                   153
#define IDI_ICN_BKMK                    154
#define IDD_DLG_SPLT_FILE               157
#define IDD_FILE_EXPORT                 158
#define IDD_DLG_TRANSF                  159
#define IDC_LST_BEGIN                   1004
#define IDC_LST_END                     1005
#define IDC_EDT_BEGIN                   1006
#define IDC_EDT_END                     1007
#define IDC_OPT_ADD                     1008
#define IDC_OPT_REMOVE                  1009
#define IDC_CHK_SELECT                  1010
#define IDC_CHK_Update                  1011
#define IDC_CHK_DELETE                  1012
#define IDC_CHK_INSERT                  1013
#define IDC_CHK_MCMD                    1014
#define IDC_CHK_SUPMOD                  1015
#define IDC_EDT_MAXLINENUM              1016
#define IDC_EDT_THRESHVAL               1017
#define IDC_EDT_TEXT                    1017
#define IDC_FIND_LST                    1018
#define IDC_CHK_LOD3000                 1018
#define IDC_IN_PRG                      1019
#define IDC_EDT_ABOUT                   1021
#define IDC_RAD_SHOWSINGLE              1022
#define IDC_RAD_SHOWALL                 1023
#define IDC_LST_MARK                    1024
#define IDC_RAD_SUPER_FLG               1024
#define IDC_RD_Value                    1025
#define IDC_RD_Range                    1026
#define IDC_RD_Beyond                   1027
#define IDC_RD_Mcmd                     1028
#define IDC_RD_Publish                  1029
#define IDC_RD_Parameter                1030
#define IDC_RD_Argument                 1031
#define IDC_RD_RPColor                  1032
#define IDC_RD_Select                   1033
#define IDC_RD_Update                   1034
#define IDC_RD_Insert                   1035
#define IDC_RD_Delete                   1036
#define IDC_RD_LPColor                  1037
#define IDC_RD_Error                    1038
#define IDC_SLD_R                       1039
#define IDC_SLD_G                       1040
#define IDC_SLD_B                       1041
#define IDC_EDT_LP                      1043
#define IDC_EDT_RP                      1044
#define IDC_STC_VAL                     1046
#define IDC_BTN_RESET                   1047
#define IDC_EDT_SPLIT_FILE_NAME         1048
#define IDC_SPLIT_OPEN_FILE             1049
#define IDC_EDT_SPLIT_SIZE              1050
#define ID_SPLT_FILE_START              1052
#define IDC_CHK_THD_SPLT                1053
#define IDC_BTN_CPALL                   1054
#define IDC_EXPORT_FILE_NAME            1055
#define IDC_EXPORT_BTN_OPEN             1056
#define IDC_EXPORT_CHK_NDOLY            1057
#define IDC_EXPORT_EDT_FRM              1058
#define IDC_EXPORT_EDT_TO               1059
#define IDC_EXPORT_CHK_SELOLY           1060
#define IDC_IPADDR                      1061
#define ID_OPT_SETTING                  32771
#define IDM_FIND_MCMD                   32772
#define ID_MENUITEM32774                32774
#define IDM_FIND_NXTMCMD                32775
#define IDM_REFRESH_VIEW                32776
#define IDM_FIND_RIGHT                  32777
#define SEPARATOR                       32778
#define IDM_PERFORM_DSP                 32781
#define IDM_VIEW_TOOLBAR                32782
#define IDM_PERFORM_ALL                 32783
#define IDM_PERFORM_SEL                 32784
#define IDM_SHOW_PARMCMD                32786
#define ID_BUTTON32788                  32788
#define IDM_SHOW_SELECT                 32790
#define IDM_SHOW_UPDATE                 32791
#define IDM_SHOW_INSERT                 32792
#define IDM_SHOW_DELETE                 32793
#define IDM_SHOW_MCMD                   32794
#define IDM_SHOW_ALL                    32795
#define ID_HIDE_APP                     32796
#define ID_SHOW_APP                     32797
#define IDM_SHOW_GRPH                   32798
#define IDM_SHOW_BKMRK                  32799
#define IDM_EXP_MCMD                    32800
#define IDM_TOG_MCMD                    32801
#define IDM_TOG_BKMK                    32802
#define IDM_SHOW_BKMK                   32803
#define IDM_CLR_BKMK                    32805
#define IDM_TOGO_BKMK                   32806
#define IDM_NAV_BKMK                    32807
#define ID_FILE_SPLIT                   32808
#define ID_FILE_EXPORT                  32809
#define ID_FILE_TRNSF                   32810
#define IDE_TOOLBAR_FIND                61204
#define IDR_MYTOOLBAR                   61205
#define IDE_TOOLBAR_SERLFT              61205
#define ID_INDICATOR_MCMD               61206
#define ID_INDICATOR_TTME               61207
#define ID_INDICATOR_ID                 61208
#define ID_INDICATOR_SELLEN             61209

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
